services:
  database:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis_data:/data

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - REDIS_HOST=database
      - REDIS_PORT=6379
    volumes:
      - ./backend/:/app
      - /app/node_modules

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/app
      - /app/node_modules
      - /app/.next